/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RadiusPairLogger_CONSTANTS_H
#define RadiusPairLogger_CONSTANTS_H

#include "RadiusPairLogger_types.h"

namespace pairer {

class RadiusPairLoggerConstants {
 public:
  RadiusPairLoggerConstants();

};

extern const RadiusPairLoggerConstants g_RadiusPairLogger_constants;

} // namespace

#endif
