/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RadiusPairLogger_constants.h"

namespace pairer {

const RadiusPairLoggerConstants g_RadiusPairLogger_constants;

RadiusPairLoggerConstants::RadiusPairLoggerConstants() {
}

} // namespace

